courier-unicode.m4: Require C++11
I ran into errors compiling on macOS related to C++11. It appears the
`configure` script didn't cause a C++ version flag (like `-std=c++11`)
to be added to the compiler.

This suggestion adds a requirement for C++11 using the
`AX_CXX_COMPILE_STDCXX_11` macro, which causes the appropriate C++
version flag to be included on macOS. Once the flag is included,
compilation with `make` succeeds.

The `AX_CXX_COMPILE_STDCXX_11` macro is part of the `autoconf-archive`
package, which is not ideal as it would add an extra dependency. A
better option would be to update the test programs in
`AC_COMPILE_IFELSE` with C++11-specific code.

Here is the error output I get when building version 2.2.4 on macOS:

    $ cd courier-unicode-2.2.4
    $ ./configure
    ...
    $ make
    /Library/Developer/CommandLineTools/usr/bin/make  all-am
    gcc -DHAVE_CONFIG_H -I.     -I.. -I./.. -g -O2 -Wall -fexceptions -MT unicodetest.o -MD -MP -MF .deps/unicodetest.Tpo -c -o unicodetest.o unicodetest.c
    mv -f .deps/unicodetest.Tpo .deps/unicodetest.Po
    /bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.     -I.. -I./.. -g -O2 -Wall -fexceptions -MT unicode.lo -MD -MP -MF .deps/unicode.Tpo -c -o unicode.lo unicode.c
    libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I./.. -g -O2 -Wall -fexceptions -MT unicode.lo -MD -MP -MF .deps/unicode.Tpo -c unicode.c  -fno-common -DPIC -o .libs/unicode.o
    libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I./.. -g -O2 -Wall -fexceptions -MT unicode.lo -MD -MP -MF .deps/unicode.Tpo -c unicode.c -o unicode.o >/dev/null 2>&1
    mv -f .deps/unicode.Tpo .deps/unicode.Plo
    /bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.     -I.. -I./.. -g -O2 -Wall -fexceptions -MT unicodebuf.lo -MD -MP -MF .deps/unicodebuf.Tpo -c -o unicodebuf.lo unicodebuf.c
    libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I./.. -g -O2 -Wall -fexceptions -MT unicodebuf.lo -MD -MP -MF .deps/unicodebuf.Tpo -c unicodebuf.c  -fno-common -DPIC -o .libs/unicodebuf.o
    libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I./.. -g -O2 -Wall -fexceptions -MT unicodebuf.lo -MD -MP -MF .deps/unicodebuf.Tpo -c unicodebuf.c -o unicodebuf.o >/dev/null 2>&1
    mv -f .deps/unicodebuf.Tpo .deps/unicodebuf.Plo
    /bin/sh ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.     -I.. -I./.. -g -O2 -MT unicodecpp.lo -MD -MP -MF .deps/unicodecpp.Tpo -c -o unicodecpp.lo unicodecpp.C
    libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -I./.. -g -O2 -MT unicodecpp.lo -MD -MP -MF .deps/unicodecpp.Tpo -c unicodecpp.C  -fno-common -DPIC -o .libs/unicodecpp.o
    In file included from unicodecpp.C:8:
    ./courier-unicode.h:1577:45: warning: 'override' keyword is a C++11 extension [-Wc++11-extensions]
            int converted(const char *ptr, size_t cnt) override;
                                                       ^
    ./courier-unicode.h:1628:49: warning: 'override' keyword is a C++11 extension [-Wc++11-extensions]
            int converted(const char32_t *ptr, size_t cnt) override
                                                           ^
    ./courier-unicode.h:1730:45: warning: 'override' keyword is a C++11 extension [-Wc++11-extensions]
            int converted(const char *ptr, size_t cnt) override
                                                       ^
    ./courier-unicode.h:1856:26: warning: 'override' keyword is a C++11 extension [-Wc++11-extensions]
            int callback(int value) override;
                                    ^
    ./courier-unicode.h:2052:30: warning: 'override' keyword is a C++11 extension [-Wc++11-extensions]
            int callback(int, char32_t) override;
                                        ^
    ./courier-unicode.h:2336:6: error: no template named 'tuple' in namespace 'std'
    std::tuple<std::vector<unicode_bidi_level_t>,
    ~~~~~^
    ./courier-unicode.h:2347:6: error: no template named 'tuple' in namespace 'std'
    std::tuple<std::vector<unicode_bidi_level_t>,
    ~~~~~^
    ./courier-unicode.h:2360:22: error: expected expression
                     &reorder_callback=[](size_t, size_t){},
                                       ^
    ./courier-unicode.h:2367:23: error: expected expression
                      &reorder_callback=[](size_t, size_t){},
                                        ^
    ./courier-unicode.h:2378:5: error: expected expression
                      [](size_t) {},
                      ^
    ./courier-unicode.h:2388:4: error: expected expression
                     [](size_t) {},
                     ^
    ./courier-unicode.h:2417:18: error: expected expression
                           &lambda=[](size_t,size_t){},
                                   ^
    ./courier-unicode.h:2502:1: error: unknown type name 'constexpr'
    constexpr int decompose_flag_qc=UNICODE_DECOMPOSE_FLAG_QC;
    ^
    ./courier-unicode.h:2502:11: error: expected unqualified-id
    constexpr int decompose_flag_qc=UNICODE_DECOMPOSE_FLAG_QC;
              ^
    ./courier-unicode.h:2503:1: error: unknown type name 'constexpr'
    constexpr int decompose_flag_compat=UNICODE_DECOMPOSE_FLAG_COMPAT;
    ^
    ./courier-unicode.h:2503:11: error: expected unqualified-id
    constexpr int decompose_flag_compat=UNICODE_DECOMPOSE_FLAG_COMPAT;
              ^
    ./courier-unicode.h:2506:30: error: no member named 'tuple' in namespace 'std'
                                      const std::vector<std::tuple<size_t, size_t>>
                                                        ~~~~~^
    ./courier-unicode.h:2506:36: error: unexpected type name 'size_t': expected expression
                                      const std::vector<std::tuple<size_t, size_t>>
                                                                   ^
    ./courier-unicode.h:2512:30: error: no member named 'tuple' in namespace 'std'
                                             const std::vector<std::tuple<size_t,
                                                               ~~~~~^
    ./courier-unicode.h:2512:36: error: unexpected type name 'size_t': expected expression
                                             const std::vector<std::tuple<size_t,
                                                                          ^
    ./courier-unicode.h:2516:1: error: unknown type name 'constexpr'
    constexpr int compose_flag_removeunused=UNICODE_COMPOSE_FLAG_REMOVEUNUSED;
    ^
    ./courier-unicode.h:2516:11: error: expected unqualified-id
    constexpr int compose_flag_removeunused=UNICODE_COMPOSE_FLAG_REMOVEUNUSED;
              ^
    ./courier-unicode.h:2518:1: error: unknown type name 'constexpr'
    constexpr int compose_flag_oneshot=UNICODE_COMPOSE_FLAG_ONESHOT;
    ^
    ./courier-unicode.h:2518:11: error: expected unqualified-id
    constexpr int compose_flag_oneshot=UNICODE_COMPOSE_FLAG_ONESHOT;
              ^
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    5 warnings and 20 errors generated.
    make[1]: *** [unicodecpp.lo] Error 1
    make: *** [all] Error 2